/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author aryay
 */
public class BookingView extends javax.swing.JFrame {

    Booking booking = new Booking();

    public BookingView() {
        initComponents();
        jTextKonfirmasi.setEditable(false);
        jTextStruk.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a1 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        a3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a4 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        b1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        b3 = new javax.swing.JCheckBox();
        b2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        b4 = new javax.swing.JCheckBox();
        b5 = new javax.swing.JCheckBox();
        b6 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonKembali = new javax.swing.JButton();
        jTempat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jFilm = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jWaktu = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jType = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextKonfirmasi = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextStruk = new javax.swing.JTextArea();
        jButtonSimpan = new javax.swing.JButton();
        jButtonFood = new javax.swing.JButton();
        jButtonBeliTiket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel1.setText("S C R E E N");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        a1.setBackground(new java.awt.Color(0, 0, 80));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        a2.setBackground(new java.awt.Color(0, 0, 80));
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("A1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        a3.setBackground(new java.awt.Color(0, 0, 80));
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("A3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("A2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        a4.setBackground(new java.awt.Color(0, 0, 80));
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        a5.setBackground(new java.awt.Color(0, 0, 80));
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        jPanel1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        a6.setBackground(new java.awt.Color(0, 0, 80));
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        jPanel1.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("A6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("A5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("A4");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("B3");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        b1.setBackground(new java.awt.Color(0, 0, 80));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("B1");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        b3.setBackground(new java.awt.Color(0, 0, 80));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        b2.setBackground(new java.awt.Color(0, 0, 80));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("B2");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        b4.setBackground(new java.awt.Color(0, 0, 80));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        b5.setBackground(new java.awt.Color(0, 0, 80));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        b6.setBackground(new java.awt.Color(0, 0, 80));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("B6");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("B5");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("B4");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        c1.setBackground(new java.awt.Color(0, 0, 80));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        c2.setBackground(new java.awt.Color(0, 0, 80));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        c3.setBackground(new java.awt.Color(0, 0, 80));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("C3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("C2");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("C1");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        c4.setBackground(new java.awt.Color(0, 0, 80));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        c5.setBackground(new java.awt.Color(0, 0, 80));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        jPanel1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        c6.setBackground(new java.awt.Color(0, 0, 80));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        jPanel1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("C6");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("C5");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setText("C4");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, 280));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 550, 370));

        jButtonKembali.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonKembali.setText("HOME");
        jButtonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseClicked(evt);
            }
        });
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        jTempat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTempat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIWALK X-TIX (BANDUNG)", "SUMMARECON MALL X-TIX (BANDUNG)", "ARTHA GADING X-TIX (JAKARTA)", "BLOK M X-TIX (JAKARTA)", "CIPUTRA WORLD X-TIX (SURABAYA)", "TUNJUNGAN PLAZA  X-TIX (SURABAYA)" }));
        jPanel2.add(jTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUDUL FILM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jFilm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEMON SLAYER", "AVENGER ENDGAME", "FANTASTIC 4", "FINAL DESTINATION 6" }));
        jPanel2.add(jFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 280, 50));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("WAKTU");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jWaktu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12.00", "14.15", "16.30", "18.45", "21.30" }));
        jPanel2.add(jWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 230, 50));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TYPE");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULER (2D) - 35.000", "SWEET BOX - 60.000", "IMAX - 120.000" }));
        jPanel2.add(jType, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 230, 50));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextKonfirmasi.setColumns(20);
        jTextKonfirmasi.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextKonfirmasi.setRows(5);
        jTextKonfirmasi.setText("-");
        jScrollPane1.setViewportView(jTextKonfirmasi);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, 200));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("KONFIRMASI PILIHAN");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 530, 270));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("KOTA & TEMPAT");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("STRUK PEMBELIAN");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextStruk.setColumns(20);
        jTextStruk.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextStruk.setRows(5);
        jTextStruk.setText("-");
        jScrollPane2.setViewportView(jTextStruk);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 490, 190));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 530, 250));

        jButtonSimpan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSimpan.setText("SIMPAN PILIHAN");
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseClicked(evt);
            }
        });
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 340, 50));

        jButtonFood.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/LAPERRR .png"))); // NOI18N
        jButtonFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFoodMouseClicked(evt);
            }
        });
        jButtonFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 530, 50));

        jButtonBeliTiket.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBeliTiket.setText("BELI TIKET");
        jButtonBeliTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBeliTiketMouseClicked(evt);
            }
        });
        jButtonBeliTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeliTiketActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBeliTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 530, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void jButtonKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseClicked
        // TODO add your handling code here:
        UtamaView utama = new UtamaView();
        utama.setVisible(true);
        this.dispose();                 
    }//GEN-LAST:event_jButtonKembaliMouseClicked

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoodActionPerformed

    private void jButtonBeliTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeliTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBeliTiketActionPerformed

    private void jButtonFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFoodMouseClicked
        // TODO add your handling code here:
        FoodView utama = new FoodView();
        utama.setVisible(true);
        this.dispose();                 
        
    }//GEN-LAST:event_jButtonFoodMouseClicked

    private void jButtonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseClicked
        // TODO add your handling code here:
        booking.simpanPilihan(BookingView.this);
    }//GEN-LAST:event_jButtonSimpanMouseClicked

    private void jButtonBeliTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBeliTiketMouseClicked
        // TODO add your handling code here:
        booking.struk(this);
    }//GEN-LAST:event_jButtonBeliTiketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.JCheckBox b1;
    private javax.swing.JCheckBox b2;
    private javax.swing.JCheckBox b3;
    private javax.swing.JCheckBox b4;
    private javax.swing.JCheckBox b5;
    private javax.swing.JCheckBox b6;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JButton jButtonBeliTiket;
    private javax.swing.JButton jButtonFood;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jFilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jTempat;
    private javax.swing.JTextArea jTextKonfirmasi;
    private javax.swing.JTextArea jTextStruk;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JComboBox<String> jWaktu;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getA1() {
        return a1;
    }

    public void setA1(JCheckBox a1) {
        this.a1 = a1;
    }

    public JCheckBox getA2() {
        return a2;
    }

    public void setA2(JCheckBox a2) {
        this.a2 = a2;
    }

    public JCheckBox getA3() {
        return a3;
    }

    public void setA3(JCheckBox a3) {
        this.a3 = a3;
    }

    public JCheckBox getA4() {
        return a4;
    }

    public void setA4(JCheckBox a4) {
        this.a4 = a4;
    }

    public JCheckBox getA5() {
        return a5;
    }

    public void setA5(JCheckBox a5) {
        this.a5 = a5;
    }

    public JCheckBox getA6() {
        return a6;
    }

    public void setA6(JCheckBox a6) {
        this.a6 = a6;
    }

    public JCheckBox getB1() {
        return b1;
    }

    public void setB1(JCheckBox b1) {
        this.b1 = b1;
    }

    public JCheckBox getB2() {
        return b2;
    }

    public void setB2(JCheckBox b2) {
        this.b2 = b2;
    }

    public JCheckBox getB3() {
        return b3;
    }

    public void setB3(JCheckBox b3) {
        this.b3 = b3;
    }

    public JCheckBox getB4() {
        return b4;
    }

    public void setB4(JCheckBox b4) {
        this.b4 = b4;
    }

    public JCheckBox getB5() {
        return b5;
    }

    public void setB5(JCheckBox b5) {
        this.b5 = b5;
    }

    public JCheckBox getB6() {
        return b6;
    }

    public void setB6(JCheckBox b6) {
        this.b6 = b6;
    }

    public JCheckBox getC1() {
        return c1;
    }

    public void setC1(JCheckBox c1) {
        this.c1 = c1;
    }

    public JCheckBox getC2() {
        return c2;
    }

    public void setC2(JCheckBox c2) {
        this.c2 = c2;
    }

    public JCheckBox getC3() {
        return c3;
    }

    public void setC3(JCheckBox c3) {
        this.c3 = c3;
    }

    public JCheckBox getC4() {
        return c4;
    }

    public void setC4(JCheckBox c4) {
        this.c4 = c4;
    }

    public JCheckBox getC5() {
        return c5;
    }

    public void setC5(JCheckBox c5) {
        this.c5 = c5;
    }

    public JCheckBox getC6() {
        return c6;
    }

    public void setC6(JCheckBox c6) {
        this.c6 = c6;
    }

    public JButton getjButtonBeliTiket() {
        return jButtonBeliTiket;
    }

    public void setjButtonBeliTiket(JButton jButtonBeliTiket) {
        this.jButtonBeliTiket = jButtonBeliTiket;
    }

    public JButton getjButtonFood() {
        return jButtonFood;
    }

    public void setjButtonFood(JButton jButtonFood) {
        this.jButtonFood = jButtonFood;
    }

    public JButton getjButtonKembali() {
        return jButtonKembali;
    }

    public void setjButtonKembali(JButton jButtonKembali) {
        this.jButtonKembali = jButtonKembali;
    }

    public JButton getjButtonSimpan() {
        return jButtonSimpan;
    }

    public void setjButtonSimpan(JButton jButtonSimpan) {
        this.jButtonSimpan = jButtonSimpan;
    }

    public JComboBox<String> getjFilm() {
        return jFilm;
    }

    public void setjFilm(JComboBox<String> jFilm) {
        this.jFilm = jFilm;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JComboBox<String> getjTempat() {
        return jTempat;
    }

    public void setjTempat(JComboBox<String> jTempat) {
        this.jTempat = jTempat;
    }

    public JTextArea getjTextKonfirmasi() {
        return jTextKonfirmasi;
    }

    public void setjTextKonfirmasi(JTextArea jTextKonfirmasi) {
        this.jTextKonfirmasi = jTextKonfirmasi;
    }

    public JTextArea getjTextStruk() {
        return jTextStruk;
    }

    public void setjTextStruk(JTextArea jTextStruk) {
        this.jTextStruk = jTextStruk;
    }

    public JComboBox<String> getjType() {
        return jType;
    }

    public void setjType(JComboBox<String> jType) {
        this.jType = jType;
    }

    public JComboBox<String> getjWaktu() {
        return jWaktu;
    }

    public void setjWaktu(JComboBox<String> jWaktu) {
        this.jWaktu = jWaktu;
    }
}
