package tugasbesar;

public class UtamaView extends javax.swing.JFrame {

    /**
     * Creates new form UtamaView
     */
    public UtamaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBioskop = new javax.swing.JButton();
        jButtonMovie = new javax.swing.JButton();
        jButtonFood = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButtonBook = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/Logo Bioskop.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Experience Every Frame");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jButtonBioskop.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonBioskop.setText("BIOSKOP");
        jButtonBioskop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBioskopMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBioskop, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 130, 50));

        jButtonMovie.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMovie.setText("MOVIE");
        jButtonMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMovieMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 130, 50));

        jButtonFood.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonFood.setText("X-FOOD");
        jButtonFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFoodMouseClicked(evt);
            }
        });
        jButtonFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 130, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/PosterIklan.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 340, 170));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/PosterIklanJumbo.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 180));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 340, 170));

        jButtonBook.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonBook.setText("BOOK");
        jButtonBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBookMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 130, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Booking Disini >>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sedang Populer");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/PosterDemon.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 210, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/PosterEndGame.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 210, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 680, 350));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JAKARTA - BANDUNG - SURABAYA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoodActionPerformed

    private void jButtonBioskopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBioskopMouseClicked
        // TODO add your handling code here:
        BioskopView bioskop = new BioskopView();
        bioskop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBioskopMouseClicked

    private void jButtonBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBookMouseClicked
        // TODO add your handling code here:
        BookingView booking = new BookingView();
        booking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBookMouseClicked

    private void jButtonFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFoodMouseClicked
        // TODO add your handling code here:
        FoodView utama = new FoodView();
        utama.setVisible(true);
        this.dispose();          
    }//GEN-LAST:event_jButtonFoodMouseClicked

    private void jButtonMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMovieMouseClicked
        // TODO add your handling code here:
        MovieView movie = new MovieView();
        movie.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jButtonMovieMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtamaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBioskop;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonFood;
    private javax.swing.JButton jButtonMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}